"""
NidhiRakshak — detection pipeline
=====================================
Feature engineering + explainable rule checks + Isolation Forest, producing:
  - work-level risk scores with full reason breakdowns
  - MP-level and state-level rollups
  - detector accuracy benchmarked against the SYNTHETIC ground-truth column
    generated by generate_dataset.py (clearly a simulated benchmark, not a
    real-world validated fraud rate)

All outputs are written as JSON into data/ for the static dashboard.
"""
import pandas as pd
import numpy as np
import json
from pathlib import Path
from sklearn.ensemble import IsolationForest
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import (precision_score, recall_score, f1_score,
                              accuracy_score, roc_auc_score, roc_curve,
                              confusion_matrix)

PIPE_DIR = Path(__file__).resolve().parent
SITE_DATA_DIR = PIPE_DIR.parent / "data"

REASON_CATALOG = {
    "LOW_UTILIZATION": {
        "label": "Low fund utilization",
        "detail": "Less than 50% of sanctioned funds spent despite the work not being marked Completed.",
        "weight": 14,
    },
    "COST_INFLATION": {
        "label": "Cost far above category norm",
        "detail": "Sanctioned cost is more than double the median cost for this work category.",
        "weight": 16,
    },
    "EXCESS_DELAY": {
        "label": "Abnormally long completion time",
        "detail": "Took more than 2x the typical completion time for this category.",
        "weight": 12,
    },
    "AGENCY_CONCENTRATION": {
        "label": "Single agency dominance",
        "detail": "One implementing agency handles an unusually high share of this MP's works.",
        "weight": 10,
    },
    "DUPLICATE_DESCRIPTION": {
        "label": "Near-duplicate / vague description",
        "detail": "Work description is near-identical to another work, or generically vague, hindering verification.",
        "weight": 12,
    },
    "ROUND_NUMBER_COST": {
        "label": "Suspiciously round sanctioned amount",
        "detail": "Cost sanctioned is an unusually round figure (e.g. exact multiple of ₹10,000), atypical for itemised estimates.",
        "weight": 6,
    },
    "YEAR_END_RUSH": {
        "label": "Year-end rush sanction",
        "detail": "Sanctioned in Jan-Mar, consistent with 'use-it-or-lose-it' spending pressure rather than planned need.",
        "weight": 6,
    },
    "WORK_SPLITTING": {
        "label": "Possible work-splitting",
        "detail": "Cost sits just under a scrutiny threshold and matches other same-day, same-agency sanctions — a known tactic to avoid higher approval levels.",
        "weight": 14,
    },
    "SHELL_AGENCY_PATTERN": {
        "label": "Agency operates across distant MPs with high flag rate",
        "detail": "This implementing agency has an unusually high flag rate across many different MPs/districts, atypical for a genuine local contractor.",
        "weight": 14,
    },
    "STALLED_STATUS": {
        "label": "Stalled after partial payment",
        "detail": "Substantial funds released but work is stalled or not started — a common precursor to fund misappropriation.",
        "weight": 10,
    },
    "STATISTICAL_ANOMALY": {
        "label": "Multivariate statistical anomaly",
        "detail": "Isolation Forest flagged this work's overall feature combination as an outlier, even where no single rule crosses its threshold.",
        "weight": 22,
    },
    "CROSS_SCHEME_DUPLICATE": {
        "label": "Possible cross-scheme duplicate funding",
        "detail": "A matching asset (same district, category and near-identical cost within an overlapping sanction window) also appears in a synthetic MGNREGS / state-scheme feed — consistent with the same physical asset being billed twice across schemes.",
        "weight": 18,
    },
}

CROSS_SCHEME_NAMES = ["MGNREGS", "State Rural Infrastructure Scheme", "State Urban Development Scheme"]


def generate_cross_scheme_dataset(df, seed=42, match_fraction=0.05, extra_unmatched=700):
    """Simulate an external cross-scheme feed (MGNREGS + state schemes) that a real
    deployment would pull via API from the respective nodal ministries/departments.
    A subset of records are constructed to overlap with existing MPLADS works
    (same district + asset category + cost within ~15% + nearby sanction window)
    to demonstrate duplicate-funding detection once that access exists.
    This is entirely SYNTHETIC_DEMO_DATA — no real MGNREGS or state-scheme data is used."""
    rng = np.random.default_rng(seed)
    n_match = max(1, int(len(df) * match_fraction))
    matched_idx = rng.choice(df.index.values, size=n_match, replace=False)
    matched_rows = df.loc[matched_idx]

    records = []
    for i, (_, row) in enumerate(matched_rows.iterrows()):
        scheme = CROSS_SCHEME_NAMES[int(rng.integers(0, len(CROSS_SCHEME_NAMES)))]
        cost_variance = rng.uniform(-0.12, 0.12)
        scheme_cost = round(float(row["cost_sanctioned"]) * (1 + cost_variance), 2)
        scheme_date = row["sanction_date"] + pd.Timedelta(days=int(rng.integers(-60, 120)))
        confidence = round(float(rng.uniform(0.68, 0.97)), 2)
        records.append({
            "scheme_record_id": f"XS{i + 1:05d}",
            "scheme": scheme,
            "state": row["state"], "district": row["district"],
            "asset_category": row["work_category"],
            "asset_description": row["work_description"],
            "cost": scheme_cost,
            "sanction_date": scheme_date.strftime("%Y-%m-%d"),
            "matched_mplads_work_id": row["work_id"],
            "match_confidence": confidence,
            "match_basis": "district + asset category + cost within ±15% + overlapping sanction window",
            "record_source": "SYNTHETIC_DEMO_DATA",
        })

    categories = df["work_category"].unique().tolist()
    states_list = df["state"].unique().tolist()
    districts_map = df.groupby("state")["district"].unique().to_dict()
    for i in range(extra_unmatched):
        st = states_list[int(rng.integers(0, len(states_list)))]
        dist_options = districts_map.get(st)
        if dist_options is None or len(dist_options) == 0:
            dist_options = [f"{st} District"]
        dist = dist_options[int(rng.integers(0, len(dist_options)))]
        cat = categories[int(rng.integers(0, len(categories)))]
        cost = round(float(rng.uniform(150000, 2500000)), 2)
        date = pd.Timestamp("2023-01-01") + pd.Timedelta(days=int(rng.integers(0, 900)))
        scheme = CROSS_SCHEME_NAMES[int(rng.integers(0, len(CROSS_SCHEME_NAMES)))]
        records.append({
            "scheme_record_id": f"XS{n_match + i + 1:05d}",
            "scheme": scheme,
            "state": st, "district": dist,
            "asset_category": cat,
            "asset_description": f"{cat} under {scheme} — {dist}",
            "cost": cost,
            "sanction_date": date.strftime("%Y-%m-%d"),
            "matched_mplads_work_id": None,
            "match_confidence": None,
            "match_basis": None,
            "record_source": "SYNTHETIC_DEMO_DATA",
        })

    matched_ids = set(matched_rows["work_id"].tolist())
    return records, matched_ids


def apply_cross_scheme_flag(df, matched_ids):
    df = df.copy()

    def add_code(row):
        codes = list(row["rule_reason_codes"])
        if row["work_id"] in matched_ids:
            codes.append("CROSS_SCHEME_DUPLICATE")
        return codes

    df["rule_reason_codes"] = df.apply(add_code, axis=1)
    df["rule_flag_count"] = df["rule_reason_codes"].apply(len)
    return df





def load_data():
    df = pd.read_csv(f"{PIPE_DIR}/mplads_work_data.csv",
                      parse_dates=["sanction_date", "completion_date"])
    return df


def engineer_features(df):
    df = df.copy()
    df["utilization_ratio"] = df["expenditure"] / df["cost_sanctioned"]
    df["completion_lag_days"] = (df["completion_date"] - df["sanction_date"]).dt.days

    cat_median_cost = df.groupby("work_category")["cost_sanctioned"].transform("median")
    df["cost_ratio_to_category_median"] = df["cost_sanctioned"] / cat_median_cost

    cat_median_lag = df.groupby("work_category")["completion_lag_days"].transform("median")
    df["lag_ratio_to_category_median"] = df["completion_lag_days"] / cat_median_lag.replace(0, np.nan)

    agency_counts = df.groupby(["mp_id", "implementing_agency"])["work_id"].transform("count")
    total_mp_works = df.groupby("mp_id")["work_id"].transform("count")
    df["agency_concentration"] = agency_counts / total_mp_works

    df["sanction_month"] = df["sanction_date"].dt.month
    df["is_year_end_rush"] = df["sanction_month"].isin([1, 2, 3])

    df["is_round_number"] = (df["cost_sanctioned"] % 10000 == 0)

    # work-splitting signal: same mp + agency + sanction_date, cost just under 1,000,000
    df["same_day_batch_key"] = (df["mp_id"].astype(str) + "_" +
                                 df["implementing_agency"].astype(str) + "_" +
                                 df["sanction_date"].dt.strftime("%Y-%m-%d"))
    batch_counts = df.groupby("same_day_batch_key")["work_id"].transform("count")
    df["is_near_threshold"] = df["cost_sanctioned"].between(850000, 999999)
    df["is_possible_split"] = df["is_near_threshold"] & (batch_counts >= 2)

    # shell-agency pattern: agency's overall flag-worthy rate (computed after rule pass, see below)
    return df


def flag_duplicate_descriptions(df, similarity_threshold=0.82):
    df = df.copy()
    df["is_duplicate_suspect"] = False
    df["duplicate_match_id"] = ""
    vague_set = {
        "development work as per requirement", "general infrastructure improvement",
        "construction of community asset", "basic amenity provision work",
        "miscellaneous civil work as needed", "infrastructure upgrade work",
    }
    df["is_vague_description"] = df["work_description"].str.lower().isin(vague_set)

    for district, group in df.groupby("district"):
        if len(group) < 2:
            continue
        vectorizer = TfidfVectorizer(stop_words="english")
        try:
            tfidf = vectorizer.fit_transform(group["work_description"])
        except ValueError:
            continue
        sim_matrix = cosine_similarity(tfidf)
        np.fill_diagonal(sim_matrix, 0)
        idx_list = group.index.tolist()
        for i, idx_i in enumerate(idx_list):
            max_sim_idx = sim_matrix[i].argmax()
            max_sim = sim_matrix[i][max_sim_idx]
            if max_sim >= similarity_threshold:
                df.loc[idx_i, "is_duplicate_suspect"] = True
                df.loc[idx_i, "duplicate_match_id"] = group.iloc[max_sim_idx]["work_id"]

    return df


def apply_rule_flags(df):
    df = df.copy()
    reason_codes_col = [[] for _ in range(len(df))]

    for i, row in enumerate(df.itertuples()):
        codes = []
        if row.utilization_ratio < 0.5 and row.status != "Completed":
            codes.append("LOW_UTILIZATION")
        if row.cost_ratio_to_category_median > 2.0:
            codes.append("COST_INFLATION")
        if not pd.isna(row.lag_ratio_to_category_median) and row.lag_ratio_to_category_median > 2.0:
            codes.append("EXCESS_DELAY")
        if row.agency_concentration > 0.4:
            codes.append("AGENCY_CONCENTRATION")
        if getattr(row, "is_duplicate_suspect", False) or getattr(row, "is_vague_description", False):
            codes.append("DUPLICATE_DESCRIPTION")
        if getattr(row, "is_round_number", False):
            codes.append("ROUND_NUMBER_COST")
        if getattr(row, "is_year_end_rush", False) and row.cost_ratio_to_category_median > 1.3:
            codes.append("YEAR_END_RUSH")
        if getattr(row, "is_possible_split", False):
            codes.append("WORK_SPLITTING")
        if row.status == "Stalled" and row.utilization_ratio > 0.4:
            codes.append("STALLED_STATUS")
        reason_codes_col[i] = codes

    df["rule_reason_codes"] = reason_codes_col
    df["rule_flag_count"] = df["rule_reason_codes"].apply(len)
    return df


def apply_shell_agency_pattern(df):
    """After an initial rule pass, find agencies with an unusually high flag rate
    across many distinct MPs — a proxy for a shell/favoured-vendor pattern."""
    df = df.copy()
    df["_prelim_flagged"] = df["rule_flag_count"] > 0
    agency_stats = df.groupby("implementing_agency").agg(
        n_mps=("mp_id", "nunique"),
        n_works=("work_id", "count"),
        flag_rate=("_prelim_flagged", "mean"),
    ).reset_index()
    risky_agencies = set(
        agency_stats[(agency_stats["n_mps"] >= 3) & (agency_stats["flag_rate"] > 0.35)]["implementing_agency"]
    )
    df["_shell_agency"] = df["implementing_agency"].isin(risky_agencies)

    def add_code(row):
        codes = list(row["rule_reason_codes"])
        if row["_shell_agency"]:
            codes.append("SHELL_AGENCY_PATTERN")
        return codes

    df["rule_reason_codes"] = df.apply(add_code, axis=1)
    df["rule_flag_count"] = df["rule_reason_codes"].apply(len)
    df = df.drop(columns=["_prelim_flagged", "_shell_agency"])
    return df, agency_stats


def run_isolation_forest(df, contamination=0.09):
    df = df.copy()
    feature_cols = [
        "utilization_ratio", "completion_lag_days", "cost_ratio_to_category_median",
        "lag_ratio_to_category_median", "agency_concentration",
    ]
    X = df[feature_cols].fillna(df[feature_cols].median())
    model = IsolationForest(contamination=contamination, random_state=42, n_estimators=200)
    df["_iso_pred"] = model.fit_predict(X)
    df["anomaly_decision_score"] = model.decision_function(X)
    df["is_statistical_anomaly"] = df["_iso_pred"] == -1

    min_s, max_s = df["anomaly_decision_score"].min(), df["anomaly_decision_score"].max()
    df["anomaly_score_normalized"] = 1 - (df["anomaly_decision_score"] - min_s) / (max_s - min_s + 1e-9)

    # feature importance proxy: correlation of each feature's deviation with anomaly score
    importances = {}
    for c in feature_cols:
        importances[c] = float(abs(np.corrcoef(X[c].fillna(0), df["anomaly_score_normalized"])[0, 1]))
    return df, importances


def compute_risk_score(df):
    df = df.copy()

    def add_stat_code(row):
        codes = list(row["rule_reason_codes"])
        if row["is_statistical_anomaly"]:
            codes.append("STATISTICAL_ANOMALY")
        return codes

    df["all_reason_codes"] = df.apply(add_stat_code, axis=1)

    def weighted_score(codes):
        raw = sum(REASON_CATALOG[c]["weight"] for c in set(codes))
        return min(raw, 100)

    df["risk_score"] = df["all_reason_codes"].apply(weighted_score).astype(float)
    # small continuous nudge from the raw anomaly score so ties separate sensibly
    df["risk_score"] = (df["risk_score"] + df["anomaly_score_normalized"] * 5).clip(0, 100).round(1)

    def band(score):
        if score >= 55:
            return "Critical"
        if score >= 35:
            return "High"
        if score >= 18:
            return "Medium"
        return "Low"

    df["risk_band"] = df["risk_score"].apply(band)
    # Keep the review queue definition consistent across every rollup:
    # only High and Critical works are counted as flagged.
    df["is_flagged"] = df["risk_band"].isin(["High", "Critical"])
    return df


def compute_accuracy_metrics(df):
    y_true = df["synthetic_ground_truth_fraud"].values
    y_pred = (df["risk_score"] >= 35).astype(int).values  # "High" or above treated as positive flag
    y_score = df["risk_score"].values / 100.0

    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()

    metrics = {
        "accuracy": round(float(accuracy_score(y_true, y_pred)), 4),
        "precision": round(float(precision_score(y_true, y_pred, zero_division=0)), 4),
        "recall": round(float(recall_score(y_true, y_pred, zero_division=0)), 4),
        "f1": round(float(f1_score(y_true, y_pred, zero_division=0)), 4),
        "roc_auc": round(float(roc_auc_score(y_true, y_score)), 4),
        "confusion_matrix": {"tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp)},
        "positives_in_data": int(y_true.sum()),
        "total_records": int(len(y_true)),
    }

    fpr, tpr, _ = roc_curve(y_true, y_score)
    idx = np.linspace(0, len(fpr) - 1, min(30, len(fpr))).astype(int)
    metrics["roc_curve"] = {"fpr": [round(float(x), 4) for x in fpr[idx]],
                             "tpr": [round(float(x), 4) for x in tpr[idx]]}
    return metrics


def reason_frequency(df):
    freq = {}
    for codes in df["all_reason_codes"]:
        for c in set(codes):
            freq[c] = freq.get(c, 0) + 1
    out = []
    for code, count in sorted(freq.items(), key=lambda x: -x[1]):
        cat = REASON_CATALOG[code]
        out.append({"code": code, "label": cat["label"], "detail": cat["detail"], "count": int(count)})
    return out


def build_json_outputs(df, agency_stats, importances, metrics):
    import os
    os.makedirs(SITE_DATA_DIR, exist_ok=True)

    # ---- national summary ----
    national = {
        "total_mps": int(df["mp_id"].nunique()),
        "total_states": int(df["state"].nunique()),
        "total_works": int(len(df)),
        "total_sanctioned": float(df["cost_sanctioned"].sum()),
        "total_expenditure": float(df["expenditure"].sum()),
        "overall_utilization_pct": round(float(df["expenditure"].sum() / df["cost_sanctioned"].sum() * 100), 2),
        "flagged_works": int((df["risk_band"].isin(["High", "Critical"])).sum()),
        "critical_works": int((df["risk_band"] == "Critical").sum()),
        "high_works": int((df["risk_band"] == "High").sum()),
        "medium_works": int((df["risk_band"] == "Medium").sum()),
        "low_works": int((df["risk_band"] == "Low").sum()),
        "flagged_mps": int(df.loc[df["risk_band"].isin(["High", "Critical"]), "mp_id"].nunique()),
        "avg_risk_score": round(float(df["risk_score"].mean()), 2),
    }

    # trend by sanction month (national)
    df["sanction_ym"] = df["sanction_date"].dt.to_period("M").astype(str)
    trend = (df.groupby("sanction_ym")
             .agg(works=("work_id", "count"),
                  flagged=("is_flagged", "sum"),
                  avg_risk=("risk_score", "mean"))
             .reset_index().sort_values("sanction_ym"))
    trend["avg_risk"] = trend["avg_risk"].round(1)
    national["monthly_trend"] = trend.to_dict(orient="records")

    cat_stats = (df.groupby("work_category")
                 .agg(works=("work_id", "count"),
                      flagged=("is_flagged", "sum"),
                      total_sanctioned=("cost_sanctioned", "sum"),
                      avg_risk=("risk_score", "mean"))
                 .reset_index().sort_values("flagged", ascending=False))
    cat_stats["avg_risk"] = cat_stats["avg_risk"].round(1)
    national["category_breakdown"] = cat_stats.to_dict(orient="records")

    with open(f"{SITE_DATA_DIR}/national.json", "w") as f:
        json.dump(national, f, indent=None, default=str)

    # ---- state rollups ----
    state_stats = (df.groupby("state")
                   .agg(mps=("mp_id", "nunique"),
                        works=("work_id", "count"),
                        total_sanctioned=("cost_sanctioned", "sum"),
                        total_expenditure=("expenditure", "sum"),
                        flagged=("is_flagged", "sum"),
                        critical=("risk_band", lambda s: (s == "Critical").sum()),
                        avg_risk=("risk_score", "mean"))
                   .reset_index().sort_values("flagged", ascending=False))
    state_stats["utilization_pct"] = (state_stats["total_expenditure"] / state_stats["total_sanctioned"] * 100).round(1)
    state_stats["avg_risk"] = state_stats["avg_risk"].round(1)
    with open(f"{SITE_DATA_DIR}/states.json", "w") as f:
        json.dump(state_stats.to_dict(orient="records"), f, default=str)

    # ---- district rollups (for state drilldown) ----
    dist_stats = (df.groupby(["state", "district"], dropna=False)
                  .agg(mps=("mp_id", "nunique"),
                       works=("work_id", "count"),
                       flagged=("is_flagged", "sum"),
                       avg_risk=("risk_score", "mean"))
                  .reset_index().sort_values("flagged", ascending=False))
    dist_stats["avg_risk"] = dist_stats["avg_risk"].round(1)
    with open(f"{SITE_DATA_DIR}/districts.json", "w") as f:
        json.dump(dist_stats.to_dict(orient="records"), f, default=str)

    # ---- MP rollups ----
    # dropna=False: a blank/NaN constituency or allocated_limit must not
    # cause pandas to silently drop that MP's row from the output — that
    # previously dropped 3 real MPs (with genuine missing-source-data gaps)
    # out of mps.json entirely.
    mp_stats = (df.groupby(["mp_id", "mp_name", "state", "constituency", "allocated_limit"], dropna=False)
                .agg(works=("work_id", "count"),
                     total_sanctioned=("cost_sanctioned", "sum"),
                     total_expenditure=("expenditure", "sum"),
                     flagged=("is_flagged", "sum"),
                     critical=("risk_band", lambda s: (s == "Critical").sum()),
                     avg_risk=("risk_score", "mean"),
                     max_risk=("risk_score", "max"))
                .reset_index().sort_values("avg_risk", ascending=False))
    mp_stats["utilization_pct"] = (mp_stats["total_expenditure"] / mp_stats["total_sanctioned"] * 100).round(1)
    mp_stats["avg_risk"] = mp_stats["avg_risk"].round(1)
    with open(f"{SITE_DATA_DIR}/mps.json", "w") as f:
        json.dump(mp_stats.to_dict(orient="records"), f, default=str)

    # ---- work-level (flagged only, to keep payload sane) + all works summary fields ----
    work_cols = [
        "work_id", "mp_id", "mp_name", "state", "district", "constituency",
        "work_category", "work_description", "implementing_agency",
        "sanction_date", "cost_sanctioned", "expenditure", "utilization_ratio",
        "completion_date", "completion_lag_days", "status", "risk_score",
        "risk_band", "all_reason_codes", "cost_ratio_to_category_median",
        "lag_ratio_to_category_median", "agency_concentration",
        "anomaly_score_normalized", "is_statistical_anomaly",
        "synthetic_ground_truth_fraud",
    ]
    export = df[work_cols].copy()
    export["sanction_date"] = export["sanction_date"].dt.strftime("%Y-%m-%d")
    export["completion_date"] = export["completion_date"].dt.strftime("%Y-%m-%d")
    export["utilization_ratio"] = export["utilization_ratio"].round(3)
    export["cost_ratio_to_category_median"] = export["cost_ratio_to_category_median"].round(2)
    export["lag_ratio_to_category_median"] = export["lag_ratio_to_category_median"].round(2)
    export["agency_concentration"] = export["agency_concentration"].round(2)
    export["anomaly_score_normalized"] = export["anomaly_score_normalized"].round(3)

    all_works = export.to_dict(orient="records")
    with open(f"{SITE_DATA_DIR}/works_all.json", "w") as f:
        json.dump(all_works, f, default=str)

    flagged_works = export[export["risk_band"].isin(["High", "Critical"])].sort_values(
        "risk_score", ascending=False
    ).to_dict(orient="records")
    with open(f"{SITE_DATA_DIR}/works_flagged.json", "w") as f:
        json.dump(flagged_works, f, default=str)

    # ---- reason catalog + frequency ----
    freq = reason_frequency(df)
    with open(f"{SITE_DATA_DIR}/reasons.json", "w") as f:
        json.dump({"catalog": REASON_CATALOG, "frequency": freq}, f, default=str)

    # ---- model metrics ----
    metrics_out = dict(metrics)
    metrics_out["feature_importance"] = {k: round(v, 3) for k, v in importances.items()}
    metrics_out["top_agencies_flagged"] = (
        agency_stats.sort_values("flag_rate", ascending=False).head(10)
        .assign(flag_rate=lambda d: d["flag_rate"].round(3))
        .to_dict(orient="records")
    )
    with open(f"{SITE_DATA_DIR}/metrics.json", "w") as f:
        json.dump(metrics_out, f, default=str)

    print("JSON outputs written to", SITE_DATA_DIR)
    print("National:", national["total_works"], "works,", national["flagged_works"], "flagged")
    print("Metrics:", metrics)


def main():
    print("Loading data...")
    df = load_data()

    print("Engineering features...")
    df = engineer_features(df)

    print("Checking descriptions for duplication/vagueness...")
    df = flag_duplicate_descriptions(df)

    print("Applying rule-based checks...")
    df = apply_rule_flags(df)

    print("Detecting shell-agency patterns...")
    df, agency_stats = apply_shell_agency_pattern(df)

    print("Generating synthetic cross-scheme feed (MGNREGS / state schemes) and matching...")
    cross_scheme_records, matched_ids = generate_cross_scheme_dataset(df)
    df = apply_cross_scheme_flag(df, matched_ids)

    print("Running Isolation Forest...")
    df, importances = run_isolation_forest(df)

    print("Computing composite risk scores...")
    df = compute_risk_score(df)

    print("Benchmarking accuracy against synthetic ground truth...")
    metrics = compute_accuracy_metrics(df)

    print("Writing JSON outputs for the dashboard...")
    build_json_outputs(df, agency_stats, importances, metrics)

    with open(f"{SITE_DATA_DIR}/cross_scheme.json", "w") as f:
        json.dump({
            "records": cross_scheme_records,
            "summary": {
                "total_scheme_records": len(cross_scheme_records),
                "matched_records": len(matched_ids),
                "schemes_covered": CROSS_SCHEME_NAMES,
                "note": ("Synthetic demo feed simulating MGNREGS + state-scheme submissions. "
                         "Real cross-scheme integration requires API/data-sharing access from "
                         "the MGNREGS nodal ministry and respective state implementing departments."),
            },
        }, f, default=str)

    df.to_csv(f"{PIPE_DIR}/flagged_works_full.csv", index=False)
    print("Done.")


if __name__ == "__main__":
    main()
